/**
 * Demo portfolio: 20 mock football cards.
 *
 * The artwork in assets/cards/ is generated by tools/generate-card-art.mjs, so the
 * whole portfolio works offline with nothing hotlinked. Prices, grades and cert
 * numbers are realistic placeholders for a graded modern-football collection.
 *
 * Cards added through the app are stored separately in localStorage and merged
 * with this list at runtime (see app.js).
 */
window.DEMO_CARDS = [
  { id: 'demo-01', name: 'Patrick Mahomes', set: 'Prizmatic', year: 2024, team: 'Kansas City Chiefs', position: 'QB', parallel: 'Gold Vinyl', price: 312, psa: 10, cert: '84120337', addedAt: '2026-08-29', image: 'assets/cards/01-mahomes.svg' },
  { id: 'demo-02', name: 'Josh Allen', set: 'Velocity', year: 2023, team: 'Buffalo Bills', position: 'QB', parallel: 'Silver SP', price: 184, psa: 10, cert: '79441802', addedAt: '2026-05-14', image: 'assets/cards/02-allen.svg' },
  { id: 'demo-03', name: 'Justin Jefferson', set: 'Mosaic Blaze', year: 2023, team: 'Minnesota Vikings', position: 'WR', parallel: 'Reactive SSP', price: 268, psa: 10, cert: '81003914', addedAt: '2026-09-02', image: 'assets/cards/03-jefferson.svg' },
  { id: 'demo-04', name: "Ja'Marr Chase", set: 'Apex Chrome', year: 2021, team: 'Cincinnati Bengals', position: 'WR', parallel: 'Rookie Refractor', price: 425, psa: 10, cert: '70558127', addedAt: '2025-11-21', image: 'assets/cards/04-chase.svg' },
  { id: 'demo-05', name: 'Christian McCaffrey', set: 'Legacy Select', year: 2023, team: 'San Francisco 49ers', position: 'RB', parallel: 'Field Level SP', price: 96.5, psa: 9, cert: '78210644', addedAt: '2026-03-07', image: 'assets/cards/05-mccaffrey.svg' },
  { id: 'demo-06', name: 'Jalen Hurts', set: 'Kinetic', year: 2022, team: 'Philadelphia Eagles', position: 'QB', parallel: 'Emerald /99', price: 239, psa: 10, cert: '76620015', addedAt: '2026-06-30', image: 'assets/cards/06-hurts.svg' },
  { id: 'demo-07', name: 'Joe Burrow', set: 'Prizmatic', year: 2020, team: 'Cincinnati Bengals', position: 'QB', parallel: 'Rookie Base', price: 675, psa: 10, cert: '66104488', addedAt: '2025-09-18', image: 'assets/cards/07-burrow.svg' },
  { id: 'demo-08', name: 'Micah Parsons', set: 'Titanium', year: 2021, team: 'Dallas Cowboys', position: 'LB', parallel: 'Rookie Base', price: 148, psa: 10, cert: '71992306', addedAt: '2026-01-26', image: 'assets/cards/08-parsons.svg' },
  { id: 'demo-09', name: 'Travis Kelce', set: 'Gridiron Royalty', year: 2022, team: 'Kansas City Chiefs', position: 'TE', parallel: 'On-Card Auto', price: 389, psa: 9, cert: '74830221', addedAt: '2026-04-11', image: 'assets/cards/09-kelce.svg' },
  { id: 'demo-10', name: 'Tyreek Hill', set: 'Velocity', year: 2023, team: 'Miami Dolphins', position: 'WR', parallel: 'Aqua /25', price: 520, psa: 10, cert: '80117459', addedAt: '2026-07-19', image: 'assets/cards/10-hill.svg' },
  { id: 'demo-11', name: 'Lamar Jackson', set: 'Spectra', year: 2023, team: 'Baltimore Ravens', position: 'QB', parallel: 'Neon Purple', price: 211, psa: 10, cert: '79008732', addedAt: '2026-02-14', image: 'assets/cards/11-jackson.svg' },
  { id: 'demo-12', name: 'C.J. Stroud', set: 'Apex Chrome', year: 2023, team: 'Houston Texans', position: 'QB', parallel: 'Rookie Refractor', price: 199, psa: 10, cert: '80664190', addedAt: '2026-08-05', image: 'assets/cards/12-stroud.svg' },
  { id: 'demo-13', name: 'Bijan Robinson', set: 'Mosaic Blaze', year: 2023, team: 'Atlanta Falcons', position: 'RB', parallel: 'Rookie Base', price: 74, psa: 9, cert: '80231776', addedAt: '2026-09-11', image: 'assets/cards/13-robinson.svg' },
  { id: 'demo-14', name: 'Saquon Barkley', set: 'Kinetic', year: 2024, team: 'Philadelphia Eagles', position: 'RB', parallel: 'On-Card Auto', price: 264, psa: 10, cert: '85002641', addedAt: '2026-06-02', image: 'assets/cards/14-barkley.svg' },
  { id: 'demo-15', name: 'CeeDee Lamb', set: 'Spectra', year: 2022, team: 'Dallas Cowboys', position: 'WR', parallel: 'Nebula SSP', price: 118, psa: 9, cert: '75513098', addedAt: '2025-12-09', image: 'assets/cards/15-lamb.svg' },
  { id: 'demo-16', name: 'Caleb Williams', set: 'Hall Pass', year: 2024, team: 'Chicago Bears', position: 'QB', parallel: 'Rookie Base', price: 342, psa: 10, cert: '85117420', addedAt: '2026-09-14', image: 'assets/cards/16-williams.svg' },
  { id: 'demo-17', name: 'Brock Purdy', set: 'Legacy Select', year: 2022, team: 'San Francisco 49ers', position: 'QB', parallel: 'Rookie Base', price: 296, psa: 10, cert: '76004513', addedAt: '2026-05-27', image: 'assets/cards/17-purdy.svg' },
  { id: 'demo-18', name: 'Aaron Donald', set: 'Titanium', year: 2021, team: 'Los Angeles Rams', position: 'DT', parallel: 'Gold Shield', price: 167, psa: 10, cert: '72440819', addedAt: '2026-03-23', image: 'assets/cards/18-donald.svg' },
  { id: 'demo-19', name: 'Garrett Wilson', set: 'Gridiron Royalty', year: 2022, team: 'New York Jets', position: 'WR', parallel: 'Crown SP', price: 63.5, psa: 9, cert: '75880264', addedAt: '2026-07-31', image: 'assets/cards/19-wilson.svg' },
  { id: 'demo-20', name: 'Nico Collins', set: 'Hall Pass', year: 2021, team: 'Houston Texans', position: 'WR', parallel: 'Rookie Base', price: 88, psa: 10, cert: '71336905', addedAt: '2026-04-28', image: 'assets/cards/20-collins.svg' },
];
